// Code generated by go generate; DO NOT EDIT.
package ncs

type Genre string

const (
	AlternativeDance Genre = "Alternative Dance"
	AlternativePop   Genre = "Alternative Pop"
	Ambient          Genre = "Ambient"
	AntiPop          Genre = "Anti-Pop"
	Bass             Genre = "Bass"
	BassHouse        Genre = "Bass House"
	BassMusic        Genre = "Bass Music"
	BrazilianPhonk   Genre = "Brazilian Phonk"
	Breakbeat        Genre = "Breakbeat"
	Chill            Genre = "Chill"
	ChillBass        Genre = "Chill Bass"
	ChillPop         Genre = "Chill Pop"
	ColourBass       Genre = "Colour Bass"
	Complextro       Genre = "Complextro"
	DancePop         Genre = "Dance-Pop"
	DeepHouse        Genre = "Deep House"
	Disco            Genre = "Disco"
	DiscoHouse       Genre = "Disco House"
	DrumBass         Genre = "Drum & Bass"
	Drumstep         Genre = "Drumstep"
	Dubstep          Genre = "Dubstep"
	EDM              Genre = "EDM"
	Electro          Genre = "Electro"
	ElectroHouse     Genre = "Electro House"
	Electronic       Genre = "Electronic"
	ElectronicPop    Genre = "Electronic Pop"
	ElectronicRock   Genre = "Electronic Rock"
	FutureBass       Genre = "Future Bass"
	FutureBounce     Genre = "Future Bounce"
	FutureFunk       Genre = "Future Funk"
	FutureHouse      Genre = "Future House"
	FutureRave       Genre = "Future Rave"
	FutureTrap       Genre = "Future Trap"
	Futurepop        Genre = "Futurepop"
	Garage           Genre = "Garage"
	GlitchHop        Genre = "Glitch Hop"
	Hardcore         Genre = "Hardcore"
	Hardstyle        Genre = "Hardstyle"
	House            Genre = "House"
	Hyperpop         Genre = "Hyperpop"
	IndieDance       Genre = "Indie Dance"
	JPop             Genre = "J-Pop"
	JerseyClub       Genre = "Jersey Club"
	JumpUp           Genre = "Jump-Up"
	LiquidDnB        Genre = "Liquid DnB"
	LofiHipHop       Genre = "Lofi Hip-Hop"
	MelodicDubstep   Genre = "Melodic Dubstep"
	MelodicHouse     Genre = "Melodic House"
	MidtempoBass     Genre = "Midtempo Bass"
	Neurofunk        Genre = "Neurofunk"
	NuJazz           Genre = "Nu-Jazz"
	Phonk            Genre = "Phonk"
	Pluggnb          Genre = "Pluggnb"
	Pop              Genre = "Pop"
	ProgressiveHouse Genre = "Progressive House"
	RnB              Genre = "RnB"
	SpeedGarage      Genre = "Speed Garage"
	TechHouse        Genre = "Tech House"
	Techno           Genre = "Techno"
	Trance           Genre = "Trance"
	Trap             Genre = "Trap"
	TribalHouse      Genre = "Tribal House"
	UKG              Genre = "UKG"
	Wave             Genre = "Wave"
	WitchHouse       Genre = "Witch House"
)

var GenreMap = map[Genre]int{
	AlternativeDance: 31,
	AlternativePop:   33,
	Ambient:          23,
	AntiPop:          34,
	Bass:             1,
	BassHouse:        18,
	BassMusic:        78,
	BrazilianPhonk:   26,
	Breakbeat:        27,
	Chill:            2,
	ChillBass:        24,
	ChillPop:         35,
	ColourBass:       85,
	Complextro:       65,
	DancePop:         36,
	DeepHouse:        66,
	Disco:            45,
	DiscoHouse:       46,
	DrumBass:         3,
	Drumstep:         4,
	Dubstep:          5,
	EDM:              6,
	Electro:          47,
	ElectroHouse:     48,
	Electronic:       7,
	ElectronicPop:    39,
	ElectronicRock:   83,
	FutureBass:       17,
	FutureBounce:     68,
	FutureFunk:       50,
	FutureHouse:      8,
	FutureRave:       69,
	FutureTrap:       57,
	Futurepop:        40,
	Garage:           51,
	GlitchHop:        15,
	Hardcore:         82,
	Hardstyle:        9,
	House:            10,
	Hyperpop:         41,
	IndieDance:       11,
	JPop:             91,
	JerseyClub:       84,
	JumpUp:           28,
	LiquidDnB:        29,
	LofiHipHop:       60,
	MelodicDubstep:   12,
	MelodicHouse:     54,
	MidtempoBass:     22,
	Neurofunk:        30,
	NuJazz:           87,
	Phonk:            16,
	Pluggnb:          86,
	Pop:              19,
	ProgressiveHouse: 55,
	RnB:              88,
	SpeedGarage:      89,
	TechHouse:        73,
	Techno:           80,
	Trance:           81,
	Trap:             14,
	TribalHouse:      74,
	UKG:              21,
	Wave:             92,
	WitchHouse:       90,
}
